[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
verbosity = 1
libs = ["../../node_modules", "../../../mud"]
src = "src"
test="src/test"
out = "out"
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
chiado = "${CHIADO_RPC_URL}"